version: '3.7'

services:

  app:
    image:  gcr.io/toptal-hub/sidekiq-health:dev
    command:
      - --worker-name-env
      - HOSTNAME
      - --redis-url-env
      - REDIS_URL
      - --sentinels-env
      - REDIS_SENTINELS
    environment:
      REDIS_URL: redis://:test1@sidekiq-master:6379/1
      REDIS_SENTINELS: redis://redis-sentinel-1:26379,redis://redis-sentinel-2:26379,redis://redis-sentinel-3:26379
    ports:
      - 8080:8080
    links:
      - redis-sentinel

  redis-master:
    image: redis:6-alpine
    command: redis-server --requirepass test1
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379 --masterauth test1
    links:
      - redis-master
    volumes:
      - "./.data:/data"

  redis-sentinel:
    deploy:
      replicas: 3
    build:
      context: ./redis-sentinel
    links:
      - redis-master
