version: '3.7'

services:

  app:
    image:  us-central1-docker.pkg.dev/toptal-hub/containers/request-validation-service-production:psre-4695-allow-redis-sentinel-connection
    environment:
      SETTINGS__CAS_PROXY__REDIS_CONFIG__NAME: sidekiq-master
      SETTINGS__CAS_PROXY__REDIS_CONFIG__SENTINELS: redis://redis-sentinel-1:26379,redis://redis-sentinel-2:26379,redis://redis-sentinel-3:26379
      SETTINGS__CAS_PROXY__REDIS_CONFIG__PASSWORD: test1
      SETTINGS__CAS_PROXY__rack_proxy__backend: 'http://fake-platform'
    links:
      - redis-sentinel

  fake-platform:
    image: traefik/whoami

  redis-master:
    image: redis:6-alpine
    command: redis-server --requirepass test1
    volumes:
      - "./.data:/data"

  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379 --masterauth test1
    links:
      - redis-master
    volumes:
      - "./.data:/data"

  redis-sentinel:
    deploy:
      replicas: 3
    build:
      context: ./redis-sentinel
    links:
      - redis-master
